#!/bin/bash

make ../output/Readme.md

{
    cat head.html

    cat <<EOF
    <main>
      <section id="Identifying">
EOF
    markdown ../output/Readme.md
    cat <<EOF
      </section>
    </main>
EOF

    echo '  <footer>'
    markdown footer.md
    echo '  </footer>'

    cat foot.html

} > ../output/index.html

